{% set version = "3.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-enrichr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/enrichR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/enrichR/enrichR_{{ version }}.tar.gz
  sha256: 43f9b7f66f76fde41bd24781e4df7a2632b4e341aec81f8c3da4d7e908767344

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-ggplot2
    - r-httr
    - r-rjson
  run:
    - r-base
    - r-ggplot2
    - r-httr
    - r-rjson

test:
  commands:
    - $R -e "library('enrichR')"           # [not win]
    - "\"%R%\" -e \"library('enrichR')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=enrichR
  license: GPL-2.0-or-later
  summary: Provides an R interface to all 'Enrichr' databases. 'Enrichr' is a web-based tool for analysing gene sets and returns any enrichment of common annotated biological features. Quoting from their website 'Enrichment analysis is a computational method for inferring knowledge about an input gene set by comparing it
    to annotated gene sets representing prior biological knowledge.' See (<http://amp.pharm.mssm.edu/Enrichr/>) for further details.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: enrichR
# Title: Provides an R Interface to 'Enrichr'
# Version: 2.0
# Authors@R: person("Wajid", "Jawaid", email = "wj241@alumni.cam.ac.uk", role = c("aut", "cre"))
# Description: Provides an R interface to all 'Enrichr' databases. 'Enrichr' is a web-based tool for analysing gene sets and returns any enrichment of common annotated biological features. Quoting from their website 'Enrichment analysis is a computational method for inferring knowledge about an input gene set by comparing it to annotated gene sets representing prior biological knowledge.' See (<http://amp.pharm.mssm.edu/Enrichr/>) for further details.
# Depends: R (>= 3.0.0)
# License: GPL (>= 2)
# Encoding: UTF-8
# LazyData: true
# Imports: httr, rjson
# RoxygenNote: 6.1.1
# Suggests: knitr, rmarkdown
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-07-18 16:36:03 UTC; wajid
# Author: Wajid Jawaid [aut, cre]
# Maintainer: Wajid Jawaid <wj241@alumni.cam.ac.uk>
# Repository: CRAN
# Date/Publication: 2019-07-25 10:10:02 UTC
