appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: dR6m0nxiOaBcZ4RR0EUnRIhkwq0IEkirR2bab2KtH/ZufmhjMedvnvKlut4G5werGDCFiicMNwxR61skduaarWkDkaodlcnEwOGZp0Ew9UqCJsRZbtJwz0NSlNqli2+383p27o7Hc+9j0tb+rX/XOBvHzClhWqNBlHlLcE0GlYcicPsH4EnLzcDkkZZb48gXMlQCISp/5RC8yzrkqYuUSyQ25KYtPIYW5ADviJRRJ3wlZpzlF+QG2AKFYNIiw//JsEevpZ6Nwa1pw13bFVbvd7ghQpYXDIRez2qT/E/VZ3VjrB7IsSy56pslZEv+gB2Wsx5J5fEgL9qsByDbu64Wnbhjk89dyGWXSLgRWJIAlJY+XI1TzELqEnFgTWS3JVH/WASQpMrUhzp7/vqCWD7nDLU0BO/odL1iAbe+oTncmSsGH8l7GHUJMObofnZQ76EupuXjThPaqiXA7eW7+XFGqhN/LwmjEglq+Rt3/zY5grWovI6fORj/medlJywPjy1cmT/RfSdoGrGMKjx6cNxrlDERKcT5wMG83Fk+LdAlc9q9+lD0paLAKdi5X1LGKGs2JVRs7mJCjjNEFXA9FVv3GbmcgTd5y1EfdsdjrqX74rfswQ2SaR4GAovozpnPJYSf/Sin3ZwKkjN8xfh4+nepy6HuFWN/OIXiplIPSkZgxLo=
conda_forge_output_validation: true
